### ISSUE TITLE
Duplicate Provider Name

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/cq-provider-sdk#118]
Currently provider Name is required in `main.go`

```
	serve.Serve(&serve.Options{
		// CHANGEME: change to your provider name
		Name:                "YourProviderName",
		Provider:            resources.Provider(),
		Logger:              nil,
		NoLogOutputOverride: false,
	})
```

and in `resources/provider.go`
```
	return &provider.Provider{
		// CHANGEME: Change to yoru provider name
		Name:      "YourProviderName",
		Configure: client.Configure,
		ResourceMap: map[string]*schema.Table{
			"demo_resource": DemoResource(),
		},
		Migrations: providerMigrations,
		Config: func() provider.Config {
			return &client.Config{}
		},
	}
```

Looks like it should be needed only in `provider.Provider`

**Comment by roneli** [comment]
This is not 100% true, since the Provider instance is not required to be `*provider.Provider` there is no promise we have the name from there. This is to allow SDK users to implement their own `CQProviderServer` based on the interface and not have to rely on the SDK default `*provider.Provider`

**Comment by yevgenypats** [comment]
I suggest then to add some documentation on which name is used when and by which component.
