### ISSUE TITLE
JSON column validation rejects []interface{} 

### ISSUE THREAD

**Issue by obataku** [cloudquery/cq-provider-sdk#36]
`TypeJSON` columns currently only accept `map`, `[]byte`, `string,` and `*string` values: https://github.com/cloudquery/cq-provider-sdk/blob/main/provider/schema/column.go#L139
```go
	// Maps are jsons
	if reflect2.TypeOf(v).Kind() == reflect.Map {
		return c.Type == TypeJSON
	}

	switch val := v.(type) {
	...
	case []byte:
		...
		return c.Type == TypeByteArray || c.Type == TypeJSON
	...
	case string:
		...
		if c.Type == TypeJSON {
			return true
		}
		...
	case *string:
		if c.Type == TypeJSON {
			return true
		}
```
... whereas postgres `json` & `jsonb` columns support JSON arrays as well as primitives and pgx accepts virtually anything it can marshal: https://github.com/jackc/pgtype/blob/master/json.go#L52-L57

at the very least it would be useful to be store JSON-serializable slices in `TypeJSON` columns

**Comment by roneli** [comment]
Supported in #50
